---
framework: jest
preRun:
     command:
        - yarn install --immutable
        - yarn workspace demo-app test-build-scripts
preMerge:
  pattern:
    - "**/__tests__/**/*-test.js"
postMerge:
  pattern: 
    - "**/__tests__/**/*-test.js"
postRun:
     command:
        - yarn --version
        - sleep 1000
version: 1.0
