---
framework: jest
preRun:
     command:
        - yarn install --immutable
        - yarn workspace demo-app test-build-scripts
preMerge:
  pattern:
    - "**/__tests__/**/*-test.js"
    - "demo-app/src/example/__tests__/Example.react-test.js"
postMerge:
  pattern: 
    - "**/__tests__/**/*-test.js"
postRun:
     command:
        - yarn --version
        - echo 'Done'
version: 1.0
